-- Run this script in your Supabase SQL Editor to create the products table and insert the Wanpy inventory.

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  sifra text not null,
  ean text not null,
  name text not null,
  category text not null,
  price numeric not null,
  image_url text not null,
  description text
);

alter table public.products enable row level security;
drop policy if exists "Allow public read access on products" on public.products;
create policy "Allow public read access on products" on public.products for select using (true);

truncate table public.products;

insert into public.products (sifra, ean, name, category, price, image_url, description) values
('WP87108', '6927749871088', 'Wanpy Cat Creamy lickable treats-chicken 70g', 'cat', 1.44, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87108 | EAN: 6927749871088'),
('WP87109', '6927749871095', 'Wanpy Cat Creamy lickable treats-tuna&shrimp 70g', 'cat', 1.44, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87109 | EAN: 6927749871095'),
('WP87123', '6927749871248', 'Wanpy Cat Creamy treat Chicken&Crab 350g', 'cat', 7.22, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87123 | EAN: 6927749871248'),
('WP87122', '6927749871231', 'Wanpy Cat Creamy treat Tuna&Crab 350g', 'cat', 7.22, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87122 | EAN: 6927749871231'),
('WP87121', '6927749871149', 'Wanpy Cat Creamy treat Tuna&Shrimp 350g', 'cat', 7.22, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87121 | EAN: 6927749871149'),
('WP81147', '6927749811473', 'Wanpy Cat Freeze dried shrimp 20g', 'cat', 2.03, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP81147 | EAN: 6927749811473'),
('WP87153', '6927749871538', 'Wanpy Cat Meat Paste Salmon&Chicken&Carrot', 'cat', 1.69, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87153 | EAN: 6927749871538'),
('WP87154', '6927749871545', 'Wanpy Cat Meat Paste Tuna&Chicken&Carrot', 'cat', 1.69, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP87154 | EAN: 6927749871545'),
('WP81129', '6927749811299', 'Wanpy Cat Soft Chicken Jerky strips 80g', 'cat', 2.46, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP81129 | EAN: 6927749811299'),
('WP81146', '6927749811466', 'Wanpy Cat Soft Duck Jerky strips 80g', 'cat', 2.46, 'https://placehold.co/300x300/f4eefa/8154a8?text=Wanpy+Cat', 'Šifra: WP81146 | EAN: 6927749811466'),
('WP89500', '6927749813088', 'Wanpy Christmas Calendars 100g', 'dog', 6.79, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP89500 | EAN: 6927749813088'),
('WP89000', '6927749813002', 'Wanpy Christmas pack, multi treats, 300g', 'dog', 6.79, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP89000 | EAN: 6927749813002'),
('WP83022', '6927749830221', 'Wanpy Dog Beef Marbled Bites 100g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP83022 | EAN: 6927749830221'),
('WP81065', '6927749810650', 'Wanpy Dog Chicken Chips 100g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81065 | EAN: 6927749810650'),
('WP81088', '6927749810889', 'Wanpy Dog Chicken Jerky & Biscuit Twists', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81088 | EAN: 6927749810889'),
('WP81035', '6927749810353', 'Wanpy Dog Chicken Jerky & Calcium Bone', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81035 | EAN: 6927749810353'),
('WP81036', '6927749810636', 'Wanpy Dog Chicken Jerky & Codfish Sandwiches', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81036 | EAN: 6927749810636'),
('WP81062', '6927749810629', 'Wanpy Dog Chicken Jerky & Codfish Sushi', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81062 | EAN: 6927749810629'),
('WP81091', '6927749810919', 'Wanpy Dog Chicken Jerky & Rawhide Twists', 'dog', 2.97, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81091 | EAN: 6927749810919'),
('WP81030', '6927749810308', 'Wanpy Dog Chicken Jerky 100 g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81030 | EAN: 6927749810308'),
('WP82035', '6927749820352', 'Wanpy Dog Duck Jerky & Rawhide wraps', 'dog', 2.97, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP82035 | EAN: 6927749820352'),
('WP82004', '6927749820048', 'Wanpy Dog Duck Jerky 100g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP82004 | EAN: 6927749820048'),
('WP82042', '6927749820420', 'Wanpy Dog Freeze dried Duck', 'dog', 2.97, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP82042 | EAN: 6927749820420'),
('WP83021', '6927749830214', 'Wanpy Dog Grilled Beef Steak 100g', 'dog', 2.97, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP83021 | EAN: 6927749830214'),
('WP87022', '6927749870227', 'Wanpy Dog Meat Paste Beef&Carrot&Pea', 'dog', 1.69, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP87022 | EAN: 6927749870227'),
('WP87021', '6927749870210', 'Wanpy Dog Meat Paste Duck&Carrot&Pea', 'dog', 1.69, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP87021 | EAN: 6927749870210'),
('WP81033', '6927749810339', 'Wanpy Dog Soft Chicken Jerky Strips 100g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP81033 | EAN: 6927749810339'),
('WP86004', '6927749860044', 'Wanpy Dog Sweet Potato Slice 100g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP86004 | EAN: 6927749860044'),
('WP86901', '6927749869016', 'Wanpy Dog Toothbrush Chews Chicken 100g', 'dog', 2.54, 'https://placehold.co/300x300/eae1f5/8154a8?text=Wanpy+Dog', 'Šifra: WP86901 | EAN: 6927749869016');
